/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author campb
 */
public class Prices extends javax.swing.JDialog {

    /**
     * Creates new form Prices
     */
    public Prices(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnmilk = new javax.swing.JButton();
        btnyogurt = new javax.swing.JButton();
        btnbutter = new javax.swing.JButton();
        btncheese = new javax.swing.JButton();
        btnfish = new javax.swing.JButton();
        btnchicken = new javax.swing.JButton();
        btnpork = new javax.swing.JButton();
        btnbeef = new javax.swing.JButton();
        btnapple = new javax.swing.JButton();
        btnbanana = new javax.swing.JButton();
        btnstrawberry = new javax.swing.JButton();
        btnoranges = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblanswer = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnmilk.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnmilk.setText("Milk");
        btnmilk.setBorder(null);
        btnmilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmilkActionPerformed(evt);
            }
        });

        btnyogurt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnyogurt.setText("Yogurt");
        btnyogurt.setBorder(null);
        btnyogurt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnyogurtActionPerformed(evt);
            }
        });

        btnbutter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbutter.setText("Butter");
        btnbutter.setBorder(null);
        btnbutter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbutterActionPerformed(evt);
            }
        });

        btncheese.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncheese.setText("Cheese");
        btncheese.setBorder(null);
        btncheese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncheeseActionPerformed(evt);
            }
        });

        btnfish.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnfish.setText("Fish");
        btnfish.setBorder(null);
        btnfish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfishActionPerformed(evt);
            }
        });

        btnchicken.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnchicken.setText("Chicken");
        btnchicken.setBorder(null);
        btnchicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnchickenActionPerformed(evt);
            }
        });

        btnpork.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnpork.setText("Pork");
        btnpork.setBorder(null);
        btnpork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnporkActionPerformed(evt);
            }
        });

        btnbeef.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbeef.setText("Beef");
        btnbeef.setBorder(null);
        btnbeef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbeefActionPerformed(evt);
            }
        });

        btnapple.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnapple.setText("Apple");
        btnapple.setBorder(null);
        btnapple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnappleActionPerformed(evt);
            }
        });

        btnbanana.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnbanana.setText("Banana");
        btnbanana.setBorder(null);
        btnbanana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbananaActionPerformed(evt);
            }
        });

        btnstrawberry.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnstrawberry.setText("Strawberry");
        btnstrawberry.setBorder(null);
        btnstrawberry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnstrawberryActionPerformed(evt);
            }
        });

        btnoranges.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnoranges.setText("Oranges");
        btnoranges.setBorder(null);
        btnoranges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnorangesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Diary");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Meats");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Fruits");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnfish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnchicken, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnpork, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbeef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnapple, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnmilk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnbanana, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnstrawberry, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnoranges, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnyogurt, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncheese, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnbutter, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btncheese, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbutter, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnyogurt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnmilk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnfish, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnchicken, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpork, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbeef, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnapple, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbanana, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnstrawberry, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnoranges, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        lblanswer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Price:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmilkActionPerformed
        lblanswer.setText("The price for milk is: $5");
    }//GEN-LAST:event_btnmilkActionPerformed

    private void btnbeefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbeefActionPerformed
        lblanswer.setText("The price for beef is: $20");
    }//GEN-LAST:event_btnbeefActionPerformed

    private void btnbananaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbananaActionPerformed
        lblanswer.setText("The price for banana is: $1.50");
    }//GEN-LAST:event_btnbananaActionPerformed

    private void btnyogurtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnyogurtActionPerformed
        lblanswer.setText("The price for yogurt is: $2");
    }//GEN-LAST:event_btnyogurtActionPerformed

    private void btncheeseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncheeseActionPerformed
        lblanswer.setText("The price for cheese is: $4");
    }//GEN-LAST:event_btncheeseActionPerformed

    private void btnbutterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbutterActionPerformed
        lblanswer.setText("The price for butter is: $3.50");
    }//GEN-LAST:event_btnbutterActionPerformed

    private void btnfishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfishActionPerformed
        lblanswer.setText("The price for fish is: $12");
    }//GEN-LAST:event_btnfishActionPerformed

    private void btnchickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnchickenActionPerformed
        lblanswer.setText("The price for chicken is: $2");
    }//GEN-LAST:event_btnchickenActionPerformed

    private void btnporkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnporkActionPerformed
       lblanswer.setText("The price for pork is: $15.25");
    }//GEN-LAST:event_btnporkActionPerformed

    private void btnappleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnappleActionPerformed
        lblanswer.setText("The price for apple is: $2");
    }//GEN-LAST:event_btnappleActionPerformed

    private void btnstrawberryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnstrawberryActionPerformed
        lblanswer.setText("The price for strawberrys is: $7");
    }//GEN-LAST:event_btnstrawberryActionPerformed

    private void btnorangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnorangesActionPerformed
        lblanswer.setText("The price for oranges is: $5.50");
    }//GEN-LAST:event_btnorangesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Prices dialog = new Prices(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnapple;
    private javax.swing.JButton btnbanana;
    private javax.swing.JButton btnbeef;
    private javax.swing.JButton btnbutter;
    private javax.swing.JButton btncheese;
    private javax.swing.JButton btnchicken;
    private javax.swing.JButton btnfish;
    private javax.swing.JButton btnmilk;
    private javax.swing.JButton btnoranges;
    private javax.swing.JButton btnpork;
    private javax.swing.JButton btnstrawberry;
    private javax.swing.JButton btnyogurt;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblanswer;
    // End of variables declaration//GEN-END:variables
}
